[build]
  command = "npm run migrate:deploy && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]
  included_files = ["node_modules/.prisma/client/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
